# Generated by Django 3.0.2 on 2020-03-13 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_auto_20200313_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtweetmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 7, 39, 41, 917577, tzinfo=utc)),
        ),
    ]
