# Generated by Django 3.0.2 on 2020-03-13 11:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns', '0003_auto_20200313_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTweetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 3, 13, 11, 16, 33, 426649, tzinfo=utc))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='NewTweetModel',
        ),
    ]
