# Generated by Django 3.0.2 on 2020-03-13 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_auto_20200313_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=200)),
                ('post_name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 3, 13, 12, 6, 53, 82686, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='MyTweetModel',
        ),
    ]
