# Generated by Django 3.0.2 on 2020-03-13 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0007_auto_20200313_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 12, 6, 57, 297858, tzinfo=utc)),
        ),
    ]
